[General]
defaultControllerID = ""
enableDiscordRPC = false
isConnectedToNetwork = false
isDevKit = false
isPS4Pro = false
isPSNSignedIn = false
isTrophyPopupDisabled = false
logFilter = ""
logType = "sync"
showSplash = false
sideTrophy = "right"
sysModulesPath = ""
trophyNotificationDuration = 6.0
userName = "RetroBat"
volumeSlider = 100

[Input]
backgroundControllerInput = false
cursorHideTimeout = 1
cursorState = 1
isMotionControlsEnabled = true
specialPadClass = 1
useSpecialPad = false
useUnifiedInputConfig = true

[Audio]
mainOutputDevice = "Default Device"
micDevice = "Default Device"
padSpkOutputDevice = "Default Device"
[GPU]
allowHDR = false
copyGPUBuffers = false
directMemoryAccess = false
dumpShaders = false
fsrEnabled = true
Fullscreen = true
FullscreenMode = "Fullscreen (Borderless)"
internalScreenHeight = 720
internalScreenWidth = 1280
nullGpu = false
patchShaders = false
presentMode = "Mailbox"
rcasAttenuation = 250
rcasEnabled = true
readbackLinearImages = false
readbacks = false
screenHeight = 720
screenWidth = 1280
vblankFrequency = 60

[Vulkan]
crashDiagnostic = false
gpuId = -1
guestMarkers = false
hostMarkers = false
rdocEnable = false
validation = false
validation_core = true
validation_gpu = false
validation_sync = false

[Debug]
CollectShader = false
ConfigVersion = "55bb7f7b9d0cf4cf476b5163fb3cb666e6c267f5"
DebugDump = false
FPSColor = true
isSeparateLogFilesEnabled = false
logEnabled = true

[Keys]
TrophyKey = ""

[GUI]
addonInstallDir = ""
installDirs = []
installDirsEnabled = [true]
saveDataPath = ""

[Settings]
consoleLanguage = 1

